export const HOME_SET_LOCATION = 'HOME_SET_LOCATION';
export const HOME_GET_STASHPOINTS_BEGIN = 'HOME_GET_STASHPOINTS_BEGIN';
export const HOME_GET_STASHPOINTS_SUCCESS = 'HOME_GET_STASHPOINTS_SUCCESS';
export const HOME_GET_STASHPOINTS_FAILURE = 'HOME_GET_STASHPOINTS_FAILURE';
export const HOME_GET_STASHPOINTS_DISMISS_ERROR = 'HOME_GET_STASHPOINTS_DISMISS_ERROR';
// AUTO MAINTAINED FILE: DO NOT CHANGE

